# Generated by Django 2.2.9 on 2020-02-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=13)),
                ('tier', models.PositiveSmallIntegerField(help_text='Defines the region of the city for fare computation.')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('mode_of_travel', models.CharField(choices=[('C', 'Company'), ('SF', 'Self')], default='C', max_length=4)),
                ('back_and_forth', models.BooleanField(default=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('RFI', 'Request for Information')], default='DRAFT', max_length=10)),
                ('approver_feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('airport_dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_dest', to='portal.Airport')),
                ('airport_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_origin', to='portal.Airport')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.Hotel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Location'),
        ),
        migrations.CreateModel(
            name='FareFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tstamp', models.DateField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Location'),
        ),
    ]
