# Generated by Django 2.2.9 on 2020-02-04 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('RFI', 'Request for Information')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
