# Generated by Django 2.2.9 on 2020-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200209_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='back_and_forth',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
