# Generated by Django 2.2.9 on 2020-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200204_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='tier',
            field=models.PositiveSmallIntegerField(help_text='Defines the region of the city for fare computation.'),
        ),
    ]
