# Generated by Django 2.2.9 on 2020-02-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_traveldetails_back_and_forth'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='airport_dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_dest', to='portal.Airport'),
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='airport_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_origin', to='portal.Airport'),
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.Hotel'),
        ),
    ]
