# Generated by Django 2.2.9 on 2020-02-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200209_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='Capacity',
            new_name='capacity',
        ),
    ]
